[[redirects]]
  from = "/api/*"
  to = "https://scriptum-sk3d.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Credentials = "true"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"